# Generated by Django 4.2.7 on 2025-05-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
