# Generated by Django 5.0.2 on 2025-03-30 20:18

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_image', models.ImageField(blank=True, help_text='Hình ảnh khuôn mặt khi điểm danh vào', null=True, upload_to=attendance.models.attendance_image_path)),
                ('check_out_image', models.ImageField(blank=True, help_text='Hình ảnh khuôn mặt khi điểm danh ra', null=True, upload_to=attendance.models.attendance_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'ordering': ['-attendance_date', '-check_in_time'],
            },
        ),
    ]
