# Generated by Django 5.1.7 on 2025-03-17 02:57

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-attendance_date', '-check_in_time']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_image',
            field=models.ImageField(blank=True, help_text='Hình ảnh khuôn mặt khi điểm danh vào', null=True, upload_to=attendance.models.attendance_image_path),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_image',
            field=models.ImageField(blank=True, help_text='Hình ảnh khuôn mặt khi điểm danh ra', null=True, upload_to=attendance.models.attendance_image_path),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='left_early',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='shift',
        ),
    ]
