# Generated by Django 5.1.7 on 2025-03-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_status_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='FaceData',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
