# Generated by Django 4.2.7 on 2025-05-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_message_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_name',
        ),
    ]
