# Generated by Django 5.0.2 on 2025-03-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_username_employee_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='user',
        ),
    ]
