# Generated by Django 5.1.7 on 2025-03-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_department_user_shift_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
