# Generated by Django 5.0.2 on 2025-04-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_alter_employee_department_and_more'),
        ('employees', '0006_alter_employee_options_rename_user_employee_username_and_more'),
    ]

    operations = [
    ]
