# Generated by Django 5.1.7 on 2025-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_department_username_alter_shift_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
