# Generated by Django 5.1.7 on 2025-03-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_department_username_alter_shift_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
